USE [master]
GO
/****** Object:  Database [ExamRedArbor]    Script Date: 11/10/2019 2:33:11 ******/
CREATE DATABASE [ExamRedArbor]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ExamRedArbor', FILENAME = N'E:\Redarbor\DB\ExamRedArbor.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ExamRedArbor_log', FILENAME = N'E:\Redarbor\DB\ExamRedArbor.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [ExamRedArbor] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ExamRedArbor].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ExamRedArbor] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [ExamRedArbor] SET ANSI_NULLS ON 
GO
ALTER DATABASE [ExamRedArbor] SET ANSI_PADDING ON 
GO
ALTER DATABASE [ExamRedArbor] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [ExamRedArbor] SET ARITHABORT ON 
GO
ALTER DATABASE [ExamRedArbor] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ExamRedArbor] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ExamRedArbor] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ExamRedArbor] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ExamRedArbor] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [ExamRedArbor] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [ExamRedArbor] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ExamRedArbor] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [ExamRedArbor] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ExamRedArbor] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ExamRedArbor] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ExamRedArbor] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ExamRedArbor] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ExamRedArbor] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ExamRedArbor] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ExamRedArbor] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ExamRedArbor] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ExamRedArbor] SET RECOVERY FULL 
GO
ALTER DATABASE [ExamRedArbor] SET  MULTI_USER 
GO
ALTER DATABASE [ExamRedArbor] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ExamRedArbor] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ExamRedArbor] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ExamRedArbor] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ExamRedArbor] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ExamRedArbor] SET QUERY_STORE = OFF
GO
USE [ExamRedArbor]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [ExamRedArbor]
GO
/****** Object:  Table [dbo].[tblEmployee]    Script Date: 11/10/2019 2:33:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblEmployee](
	[intID] [int] IDENTITY(1,1) NOT NULL,
	[intCompanyID] [int] NOT NULL,
	[dtCreatedOn] [datetime] NOT NULL,
	[dtDeletedOn] [datetime] NULL,
	[vcEmail] [nvarchar](max) NOT NULL,
	[vcFax] [nvarchar](max) NOT NULL,
	[vcName] [nvarchar](max) NOT NULL,
	[dtLastLogin] [datetime] NULL,
	[vcPassword] [nvarchar](max) NOT NULL,
	[intPortalID] [int] NOT NULL,
	[intRoleID] [int] NOT NULL,
	[intStatusID] [int] NOT NULL,
	[vcTelephone] [nvarchar](max) NOT NULL,
	[vcUpdatedOn] [datetime] NOT NULL,
	[vcUsername] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[intID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [ExamRedArbor] SET  READ_WRITE 
GO
